# Generated migration for nautobot_software_lifecycle

from django.db import migrations, models
import django.db.models.deletion
import nautobot.apps.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=None)),
                ('serial_number_pak', models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial Number / PAK number')),
                ('product_id', models.CharField(blank=True, max_length=255)),
                ('product_description', models.TextField(blank=True)),
                ('coverage', models.CharField(blank=True, max_length=255)),
                ('covered_line_status', models.CharField(blank=True, max_length=255)),
                ('business_entity', models.CharField(blank=True, max_length=255)),
                ('sub_business_entity', models.CharField(blank=True, max_length=255)),
                ('product_family', models.CharField(blank=True, max_length=255)),
                ('asset_type', models.CharField(blank=True, max_length=255)),
                ('product_type', models.CharField(blank=True, max_length=255)),
                ('buying_program', models.CharField(blank=True, max_length=255)),
                ('offer_type', models.CharField(blank=True, max_length=255)),
                ('parent_offer_type', models.CharField(blank=True, max_length=255)),
                ('pid_mapping_group', models.CharField(blank=True, max_length=255)),
                ('item_quantity', models.IntegerField(blank=True, null=True)),
                ('covered_line_start_date', models.DateField(blank=True, null=True)),
                ('covered_line_end_date', models.DateField(blank=True, null=True)),
                ('covered_line_end_date_fy', models.CharField(blank=True, max_length=50)),
                ('covered_line_end_date_fy_fq', models.CharField(blank=True, max_length=50)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('ship_date_fy', models.CharField(blank=True, max_length=50)),
                ('ship_date_fy_fq', models.CharField(blank=True, max_length=50)),
                ('end_of_product_sale_date', models.DateField(blank=True, null=True)),
                ('last_renewal_date', models.DateField(blank=True, null=True)),
                ('end_of_software_maintenance_date', models.DateField(blank=True, null=True)),
                ('last_date_of_support', models.DateField(blank=True, null=True)),
                ('ldos_fy', models.CharField(blank=True, max_length=50, verbose_name='LDOS FY')),
                ('ldos_fy_fq', models.CharField(blank=True, max_length=50, verbose_name='LDOS FY-FQ')),
                ('contract_type', models.CharField(blank=True, max_length=255)),
                ('service_brand_code', models.CharField(blank=True, max_length=255)),
                ('contract_number', models.CharField(blank=True, max_length=255)),
                ('subscription_id', models.CharField(blank=True, max_length=255)),
                ('migration_pid_flag', models.CharField(blank=True, max_length=50)),
                ('end_of_life_product_bulletin', models.CharField(blank=True, max_length=255)),
                ('mss_extended_support_assessment_result', models.CharField(blank=True, max_length=255)),
                ('mss_extended_support_end_date', models.DateField(blank=True, null=True)),
                ('mss_extended_support_approved_service_level', models.CharField(blank=True, max_length=255)),
                ('warranty_type', models.CharField(blank=True, max_length=255)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('install_site_gu_name', models.CharField(blank=True, max_length=255)),
                ('install_site_gu_id', models.CharField(blank=True, max_length=255)),
                ('install_site_cr_parent_party_name', models.CharField(blank=True, max_length=255)),
                ('install_site_cr_parent_party_id', models.CharField(blank=True, max_length=255)),
                ('install_site_cr_party_name', models.CharField(blank=True, max_length=255)),
                ('install_site_cr_party_id', models.CharField(blank=True, max_length=255)),
                ('install_site_name', models.CharField(blank=True, max_length=255)),
                ('install_site_id', models.CharField(blank=True, max_length=255)),
                ('install_site_address_1', models.CharField(blank=True, max_length=255)),
                ('install_site_city', models.CharField(blank=True, max_length=255)),
                ('install_site_state', models.CharField(blank=True, max_length=255)),
                ('install_site_country', models.CharField(blank=True, max_length=255)),
                ('install_site_postal_code', models.CharField(blank=True, max_length=255)),
                ('best_partner_be_geo_id', models.CharField(blank=True, max_length=255)),
                ('best_partner_be_geo_name', models.CharField(blank=True, max_length=255)),
                ('product_bill_to_id', models.CharField(blank=True, max_length=255)),
                ('product_bill_to_partner_name', models.CharField(blank=True, max_length=255)),
                ('product_partner_be_geo_id', models.CharField(blank=True, max_length=255)),
                ('product_partner_be_geo_name', models.CharField(blank=True, max_length=255)),
                ('pos_partner_be_geo_id', models.CharField(blank=True, max_length=255)),
                ('pos_partner_be_geo_name', models.CharField(blank=True, max_length=255)),
                ('service_bill_to_id', models.CharField(blank=True, max_length=255)),
                ('service_bill_to_partner_name', models.CharField(blank=True, max_length=255)),
                ('service_partner_be_geo_id', models.CharField(blank=True, max_length=255)),
                ('service_partner_be_geo_name', models.CharField(blank=True, max_length=255)),
                ('default_service_level', models.CharField(blank=True, max_length=255)),
                ('instance_id', models.CharField(blank=True, max_length=255)),
                ('parent_instance_id', models.CharField(blank=True, max_length=255)),
                ('product_so', models.CharField(blank=True, max_length=255)),
                ('product_po', models.CharField(blank=True, max_length=255)),
                ('service_so', models.CharField(blank=True, max_length=255)),
                ('service_po', models.CharField(blank=True, max_length=255)),
                ('web_order_id', models.CharField(blank=True, max_length=255)),
                ('mapped_to_swss', models.CharField(blank=True, max_length=10, verbose_name='Mapped to SWSS (Y/N)')),
                ('auto_renewal_flag', models.CharField(blank=True, max_length=10)),
                ('installed_base_status', models.CharField(blank=True, max_length=255)),
                ('atr_eligible', models.CharField(blank=True, max_length=10)),
                ('do_not_renew_reason', models.CharField(blank=True, max_length=255)),
                ('intended_use', models.CharField(blank=True, max_length=255)),
                ('st_eligible', models.CharField(blank=True, max_length=10)),
                ('st_current', models.CharField(blank=True, max_length=10)),
                ('license_product_id', models.CharField(blank=True, max_length=255)),
                ('ela_yorn', models.CharField(blank=True, max_length=10, verbose_name='ELA Y/N')),
                ('field_notice', models.CharField(blank=True, max_length=255)),
                ('field_notice_title', models.TextField(blank=True)),
                ('major_minor', models.CharField(blank=True, max_length=50)),
                ('configuration', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(help_text='Tenant associated with this license', on_delete=django.db.models.deletion.CASCADE, related_name='software_licenses', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Software License',
                'verbose_name_plural': 'Software Licenses',
                'ordering': ['tenant', 'product_id'],
            },
        ),
    ]
