# Generated by Django 4.2.28 on 2026-04-15 20:53

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("extras", "0133_alter_approvalworkflowstageresponse_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CiscoOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("order_number", models.CharField(max_length=255, unique=True)),
                ("customer_po_number", models.CharField(blank=True, max_length=255)),
                ("account_name", models.CharField(blank=True, max_length=255)),
                ("account_number", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(blank=True, max_length=255)),
                ("status_detail", models.CharField(blank=True, max_length=255)),
                ("lifecycle_state", models.CharField(blank=True, max_length=255)),
                ("is_tracked", models.BooleanField(default=True)),
                ("open_exception_count", models.PositiveIntegerField(default=0)),
                ("requested_delivery_date", models.DateField(blank=True, null=True)),
                ("promised_delivery_date", models.DateField(blank=True, null=True)),
                ("estimated_delivery_date", models.DateField(blank=True, null=True)),
                ("ordered_at", models.DateTimeField(blank=True, null=True)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_status",
                    models.CharField(default="pending", max_length=32),
                ),
                ("last_sync_message", models.CharField(blank=True, max_length=255)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "tags",
                    nautobot.core.models.fields.TagsField(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cisco order",
                "verbose_name_plural": "Cisco orders",
                "ordering": ["-last_synced_at", "order_number"],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CiscoOrderUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("update_type", models.CharField(max_length=32)),
                ("source", models.CharField(default="poll", max_length=16)),
                ("summary", models.CharField(max_length=255)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="nbcot.ciscoorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cisco order update",
                "verbose_name_plural": "Cisco order updates",
                "ordering": ["-occurred_at", "-created"],
            },
        ),
        migrations.CreateModel(
            name="CiscoOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("line_key", models.CharField(max_length=255)),
                ("line_number", models.CharField(blank=True, max_length=255)),
                ("sku", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(blank=True, max_length=255)),
                ("shipment_status", models.CharField(blank=True, max_length=255)),
                ("quantity_ordered", models.PositiveIntegerField(default=0)),
                ("quantity_fulfilled", models.PositiveIntegerField(default=0)),
                ("quantity_backordered", models.PositiveIntegerField(default=0)),
                ("promised_delivery_date", models.DateField(blank=True, null=True)),
                ("estimated_delivery_date", models.DateField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="nbcot.ciscoorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cisco order line",
                "verbose_name_plural": "Cisco order lines",
                "ordering": ["order__order_number", "line_number", "line_key"],
                "unique_together": {("order", "line_key")},
            },
        ),
    ]
