# Generated by Django 4.2.30 on 2026-04-15 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbcot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciscoorderupdate',
            options={'ordering': ['-occurred_at', '-id'], 'verbose_name': 'Cisco order update', 'verbose_name_plural': 'Cisco order updates'},
        ),
    ]
