---
name: "CI"
on: # yamllint disable
  - "push"
  - "pull_request"
jobs:
  yamllint:
    runs-on: [self-hosted, otepiconfig]
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Install yamllint"
        run: "python3 -m pip install --user --no-cache-dir yamllint"
      - name: "Run yamllint"
        run: "yamllint ."
